---
- name: Ensure update cache
  run_once: yes
  apt:
    update_cache: yes
- name: Ensure several components installed
  apt:
    name: "{{item.value}}"
    state: installed
  with_items: "{{packages}}"