---
- name: Ensure update cache
  run_once: no
  apt:
    update_cache: yes
- name: Ensure serveral components installed
  apt:
    name: "{{item.value}}"
    state: installed
  with_items: "{{packages}}"

